apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/data/vol/0
    server: 172.20.23.40
