apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: wordpress
  #type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: wordpress
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      name: wordpress
    matchExpressions:
      - {key: name, operator: In, values: [wordpress]}
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: sumanthkulkarni13/wp-centos:k8s
        ports:
        - containerPort: 80
          name: wordpress
      #  volumeMounts:
      #  - mountPath: /var/www/html
      #    name: my-vol                    
      #  env:
      #    - name: WORDPRESS_DB_PASSWORD
      #      value: k8spassword
      #    - name: WORDPRESS_DB_USER
      #      value: root
      #    - name: WORDPRESS_DB_HOST
      #      value: mysql
      #    - name: WORDPRESS_DB_NAME
      #      value: wordpress9
    #  volumes:
    #    - name: "my-vol"
    #      hostPath:
    #        path: "/mnt/data/web"
